### ISSUE TITLE
error asDatasorce

### ISSUE THREAD

**Issue by J-Arji** [abdullahselek/ASCollectionView#2]
hi when i run app error:
```
 2017-09-26 01:48:52.421 collectionTest[6050:90252] Unknown class _TtC16ASCollectionView16ASCollectionView in Interface Builder file.
(lldb) 
```

**Comment by abdullahselek** [comment]
Hi @J-Arji could you please tell me which ways you follow in details that you get the error? If you build and run the app which you cloned works properly.

**Comment by abdullahselek** [comment]
Closing this issue because of lack of information, you can checkout the master and see the details. If you have still any questions don't hesitate to ask me.
