### ISSUE TITLE
resize header cell

### ISSUE THREAD

**Issue by ghost** [abdullahselek/ASCollectionView#3]
How can i resize the header label and make the cell smaller

**Comment by abdullahselek** [comment]
Hey @pprevalon you can change the header cell size with
`
let asCollectionViewLayout = collectionView.collectionViewLayout as? ASCollectionViewLayout
asCollectionViewLayout?.headerSize = CGSize(width: collectionView.frame.size.width, height: 30.0)
`

and to change the label font size you can customise UILabel font size inside the `Header.xib` file.

**Comment by abdullahselek** [comment]
Hey @pprevalon I am closing this issue, if you have any other questions don't hesitate to ask.
