### ISSUE TITLE
What is  Parallax Cell ? 

### ISSUE THREAD

**Issue by sensuikan1973** [abdullahselek/ASCollectionView#5]
I would like to understand the difference between ParallaxCell and UICollectionViewCell.

**Comment by abdullahselek** [comment]
ParallaxCell extends from `ASCollectionViewParallaxCell` and **ASCollectionViewParallaxCell** gives a parallax effect when you scroll on collection view.

**Comment by sensuikan1973** [comment]
I understand! Tanks.
I will use this library.
