### ISSUE TITLE
how can i change cell size and pattern 

### ISSUE THREAD

**Issue by krutitrivedi** [abdullahselek/ASCollectionView#7]
![screen shot 2018-03-19 at 2 08 23 pm](https://user-images.githubusercontent.com/28212734/37585410-07971eae-2b7f-11e8-9777-5d27f042075d.png)
i only want pattern like shown in above screenshort

**Comment by abdullahselek** [comment]
Hi @krutitrivedi you can change sizes of header, grid cell and parallax cell with reaching to collectionview's layout. Take a look at sample code below try to modify.
`let asCollectionViewLayout = collectionView.collectionViewLayout as? ASCollectionViewLayout`
`asCollectionViewLayout?.headerSize = CGSize(width: WIDTH_VALUE_YOU_WANT, height: HEIGHT_VALUE_YOU_WANT)`
`asCollectionViewLayout?.parallaxCellSize = CGSize(width: WIDTH_VALUE_YOU_WANT, height: HEIGHT_VALUE_YOU_WANT)`
`asCollectionViewLayout?.gridCellSize = CGSize(width: WIDTH_VALUE_YOU_WANT, height: HEIGHT_VALUE_YOU_WANT)`

**Comment by krutitrivedi** [comment]
i am asking about the formatting of the cell as shown in above screenshort
i want one image in first row and in second row need two images

**Comment by abdullahselek** [comment]
Run the sample app see how it looks like then try to modify the code base in order to your needs.
